---
output: html_document
---

#####  Converting DNs to radiance
<Replace this by your explanation of your code...Please note that in order to 
use your code also as standard R script and not just in markown, you can 
write the entire core functionality in one block so you can just copy/paste it 
into a standard R script if necessary. The required visualization of band 4
should then follow in a second code block since this won't be necessary in a
standard R script.>

```{r}
# General setttings
input.path <- "..."
output.path <- "..."
...

# Install mocRS directly from GitHub and load it
library(devtools)
install_git("git://github.com/marburg-open-courseware/mocRS")
library(mocRS)

# Load other necessary libraries
...

# Get a list of the filenames of the Landsat band in the input folder
datasets <- ...

# Calibrate one band after another
sapply(datasets, function(x){
  # Load actual file x into memory
  ...
  
  # Do whatever you have to do
  ...

  # Write the actual calibrated dataset to an output file
  ...
})
```

#####  Map-type visualization of Landsat band 4
```{r, echo=FALSE}
...
```
